on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: "login to dock hub"
        run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
        
      - name: "bulding image"
        run: docker build -t ${{ secrets.DOCKER_USER }}/myimage .
        
      - name: "pushing"
        run: docker push ${{ secrets.DOCKER_USER }}/myimage
